// Generated by CoffeeScript 1.7.1
var Account, AccountSchema, Playlist, PlaylistSchema, Schema, mongoose, passportLocalMongoose;

mongoose = require('mongoose');

Playlist = require('./playlist');

PlaylistSchema = Playlist.Schema;

Schema = mongoose.Schema;

passportLocalMongoose = require('passport-local-mongoose');

AccountSchema = new Schema({
  nickname: {
    type: String,
    index: true,
    unique: true
  },
  birthdate: Date,
  playlists: [PlaylistSchema]
});

AccountSchema.plugin(passportLocalMongoose);

Account = mongoose.model('Account', AccountSchema);

module.exports = {
  Account: Account,
  Schema: AccountSchema
};
