// Generated by CoffeeScript 1.7.1
var Category, CategorySchema, mongoose;

mongoose = require('mongoose');

CategorySchema = new Schema({
  name: String,
  description: String
});

Category = mongoose.model("Category", categorySchema);

module.exports = {
  Category: Category,
  Schema: CategorySchema
};
