// Generated by CoffeeScript 1.7.1
var Category, CategorySchema, Schema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

CategorySchema = new Schema({
  name: String,
  description: String
});

Category = mongoose.model("Category", CategorySchema);

module.exports = {
  Category: Category,
  Schema: CategorySchema
};
