// Generated by CoffeeScript 1.7.1
var Page, PageSchema, Schema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

PageSchema = new Schema({
  title: {
    type: String,
    index: {
      unique: true
    }
  },
  author: String,
  route: String,
  body: String,
  creationDate: {
    type: Date,
    "default": Date.now
  },
  updateDate: {
    type: Date,
    "default": Date.now
  },
  published: Boolean
});

Page = mongoose.model('Page', PageSchema);

module.exports = {
  Page: Page,
  Schema: PageSchema
};
