// Generated by CoffeeScript 1.7.1
var Schema, User, mongoose, userSchema;

mongoose = require("mongoose");

Schema = mongoose.Schema;

userSchema = new Schema({
  firstname: String,
  lastname: String,
  email: {
    type: String,
    index: {
      unique: true
    }
  },
  password: String,
  signupDate: {
    type: Date,
    "default": Date.now
  }
}, {
  collection: "users"
});

User = mongoose.model("User", userSchema);

module.exports = {
  get: function(id, callback) {
    return User.find({
      _id: id
    }, "firstname lastname email signupDate", function(err, data, numberAffected) {
      if (!err) {
        err = null;
      }
      return callback(err, data);
    });
  },
  create: function(info, callback) {
    var newUser;
    newUser = new User(info);
    return newUser.save(function(err, newUser, numberAffected) {
      if (!err) {
        err = null;
      }
      return callback(err, newUser);
    });
  },
  remove: function(id, callback) {
    return User.remove({
      _id: id
    }, function(err, data) {
      if (!err) {
        err = null;
      }
      return callback(err, data);
    }).remove();
  },
  checkPassword: function(email, password, callback) {
    return User.find({
      email: email
    }, function(err, data) {
      if (!err) {
        err = null;
      }
      if (data.length > 0) {
        if (data[0].password === password) {
          return callback(err, {
            check: true,
            userId: data[0]._id
          });
        } else {
          return callback(err, {
            check: false,
            userId: null
          });
        }
      } else {
        return callback("User not found.");
      }
    });
  }
};
