// Generated by CoffeeScript 1.7.1
module.exports = {
  title: 'Fluid',
  port: '3333',
  env: 'development',
  menu: {
    enabled: true,
    content: [
      {
        label: 'Index',
        path: '/'
      }, {
        label: 'Blog',
        path: '/blog'
      }, {
        label: 'LinkedIn',
        path: '#'
      }, {
        label: 'GitHub',
        path: '#'
      }, {
        label: 'Contact',
        path: '/contact'
      }
    ]
  },
  routes: [
    {
      path: '/',
      view: 'index',
      title: ''
    }
  ],
  blog: {
    enabled: true
  },
  mongo: {
    development: {
      host: 'localhost',
      db: 'fluiddb_dev',
      user: '',
      password: ''
    },
    production: {
      host: 'localhost',
      db: 'fluiddb',
      user: '',
      password: ''
    }
  },
  ssl: {
    enabled: false,
    key: '',
    cert: ''
  },
  secret: 'DD9E5F7F98E47AD47932ACBF77912'
};
