// Generated by CoffeeScript 1.7.1
var markdown;

markdown = require('markdown').markdown;

module.exports = {
  slugify: function(text) {
    return text.toLowerCase().replace(/\040/g, '-').replace(/[^\w-]+/g, '');
  },
  convertMarkdown: function(markdown) {
    return markdown.toHTML(markdown);
  }
};
